# Generated by Selenium IDE


class Test():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_(self):
        self.driver.get("https://obrkarta.ru")
        self.driver.set_window_size(801, 959)
        self.driver.find_element(By.XPATH, "//a[@id=\'personal\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'login\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'login\']").send_keys("17003054")
        self.driver.find_element(By.XPATH, "//input[@name=\'password\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'password\']").send_keys("17003054")
        self.driver.find_element(By.XPATH, "//button[contains(.,\'Войти\')]").click()
        self.driver.find_element(By.XPATH, "//span[contains(.,\'Мустафин Яропол...\')]").click()
        self.driver.find_element(By.XPATH, "//a[contains(text(),\'Личные данные\')]").click()
        self.driver.find_element(By.CSS_SELECTOR, ".cabinet__item:nth-child(3) .js-change-show > .btn_style").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'limit\']").click()
        self.driver.find_element(By.XPATH, "//input[@name=\'limit\']").send_keys("0.02")
        self.driver.find_element(By.CSS_SELECTOR, ".cabinet__item:nth-child(3) .js-change-hide > .btn_style").click()
